/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2026-01-21 10:20:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.jobai.model.AIResult;
import com.jobai.model.User;

public final class ai_002dhistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.jobai.model.User");
    _jspx_imports_classes.add("com.jobai.model.AIResult");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>AI History | JobAI</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	User user = (User) session.getAttribute("loggedUser");
	if (user == null) {
		response.sendRedirect(request.getContextPath() + "/jsp/login.jsp");
		return;
	}

	List<AIResult> history = (List<AIResult>) request.getAttribute("history");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- FULL SCREEN WRAPPER -->\r\n");
      out.write("	<div class=\"login-page\">\r\n");
      out.write("\r\n");
      out.write("		<!-- WIDE PAGE -->\r\n");
      out.write("		<div class=\"ai-page\">\r\n");
      out.write("\r\n");
      out.write("			<h2>📊 Your AI Activity History</h2>\r\n");
      out.write("\r\n");
      out.write("			<p class=\"ai-desc\">View your past skill-based and resume-based AI\r\n");
      out.write("				recommendations.</p>\r\n");
      out.write("\r\n");
      out.write("			");

			if (history == null || history.isEmpty()) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<p style=\"text-align: center; font-weight: 600;\">No AI history\r\n");
      out.write("				found yet.</p>\r\n");
      out.write("\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- HISTORY TABLE -->\r\n");
      out.write("			<div class=\"history-table-wrapper\">\r\n");
      out.write("\r\n");
      out.write("				<table class=\"history-table\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>Date</th>\r\n");
      out.write("							<th>Input Type</th>\r\n");
      out.write("							<th>AI Result</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						for (AIResult r : history) {
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print(r.getCreatedAt());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(r.getInputText());
      out.write("</td>\r\n");
      out.write("							<td class=\"history-result\">");
      out.print(r.getResultText());
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- ACTIONS -->\r\n");
      out.write("			<div class=\"ai-actions\">\r\n");
      out.write("\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/skill-input.jsp\"\r\n");
      out.write("					class=\"ai-card\">\r\n");
      out.write("					<h3>Skill-Based AI</h3>\r\n");
      out.write("					<p>Run AI using skills</p>\r\n");
      out.write("				</a> <a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/resume-upload.jsp\"\r\n");
      out.write("					class=\"ai-card\">\r\n");
      out.write("					<h3>Resume-Based AI</h3>\r\n");
      out.write("					<p>Analyze resume again</p>\r\n");
      out.write("				</a> <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\"\r\n");
      out.write("					class=\"ai-card logout-card\">\r\n");
      out.write("					<h3>Logout</h3>\r\n");
      out.write("					<p>End your session</p>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
