/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2026-01-19 14:33:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jobai.model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.jobai.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JobAI | AI Job Role Recommendation</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"app-container\">\r\n");
      out.write("\r\n");
      out.write("		<!-- ================= NAVBAR ================= -->\r\n");
      out.write("		<header class=\"navbar\">\r\n");
      out.write("			<div class=\"logo\">Job Genius</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			<nav class=\"nav-links\">\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\">Home</a> <a\r\n");
      out.write("					href=\"#features\">Features</a>\r\n");
      out.write("\r\n");
      out.write("				");

				User user = (User) session.getAttribute("loggedUser");
				if (user == null) {
				
      out.write("\r\n");
      out.write("				<!-- NOT LOGGED IN -->\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/login.jsp\">Login</a> <a\r\n");
      out.write("					href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/register.jsp\">Register</a>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<!-- LOGGED IN -->\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/login-success.jsp\">\r\n");
      out.write("					Dashboard </a> <a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\">Logout</a>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("		<!-- ================= HERO SECTION ================= -->\r\n");
      out.write("		<section class=\"hero\">\r\n");
      out.write("\r\n");
      out.write("			<!-- LEFT -->\r\n");
      out.write("			<div class=\"hero-left\">\r\n");
      out.write("				<h1>AI-Powered Job Role Recommendation</h1>\r\n");
      out.write("\r\n");
      out.write("				<p>A smart platform that helps IT students discover the most\r\n");
      out.write("					suitable job roles using AI-based skill and resume analysis.</p>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"hero-buttons\">\r\n");
      out.write("					<a href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/register.jsp\"\r\n");
      out.write("						class=\"btn primary-btn\"> REGISTER </a> <a\r\n");
      out.write("						href=\"");
      out.print(request.getContextPath());
      out.write("/jsp/login.jsp\"\r\n");
      out.write("						class=\"btn secondary-btn\"> LOGIN </a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- RIGHT -->\r\n");
      out.write("			<div class=\"hero-right\">\r\n");
      out.write("				<img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/images/job.png\"\r\n");
      out.write("					alt=\"AI Job Recommendation\" class=\"hero-image\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- ================= FEATURES ================= -->\r\n");
      out.write("		<section class=\"features\" id=\"features\">\r\n");
      out.write("\r\n");
      out.write("			<h2 class=\"features-title\">What Job Genius Do</h2>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"features-container\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"feature-card\">\r\n");
      out.write("					<h3>AI Skill Analysis</h3>\r\n");
      out.write("					<p>Analyze your technical skills using AI to understand your\r\n");
      out.write("						career strengths.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"feature-card\">\r\n");
      out.write("					<h3>Resume Analyzer</h3>\r\n");
      out.write("					<p>Upload your resume and let AI extract skills, experience,\r\n");
      out.write("						and suitability.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"feature-card\">\r\n");
      out.write("					<h3>Job Role Matching</h3>\r\n");
      out.write("					<p>Get the most suitable IT job roles based on your profile.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"feature-card\">\r\n");
      out.write("					<h3>Skill Upgrade Suggestions</h3>\r\n");
      out.write("					<p>AI suggests additional skills to improve your job readiness.\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
